version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/intellmeet
      - JWT_SECRET=supersecretjwt
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    networks:
      - intellmeet_net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - intellmeet_net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - intellmeet_net

volumes:
  mongo_data:

networks:
  intellmeet_net:
    driver: bridge
